services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: "app-container"
    ports:
      - "8080:80"
    depends_on:
      - database
      - cache
    volumes:
      - ./application:/var/www/html
    env_file:
      - .app.env
  database:
    image: mariadb:11.7.2
    container_name: "database-container"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - ./database.env
  cache:
    image: redis:7-alpine
    container_name: "cache-container"
    ports:
      - "6379:6379"

volumes:
  mysqldata:
