services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: "web-container"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: "app-container"
    depends_on:
      - web
      - database
      - cache
    volumes:
      - ./application:/var/www/html
    env_file:
      - .app.env
  database:
    image: postgres:17.4
    container_name: "database-container"
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - database.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:alpine
    container_name: "cache-container"
    ports:
      - "6379:6379"

volumes:
  pgdata:
