services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: "web-container"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: "app-container"
    depends_on:
      - web
      - database
      - cache
    volumes:
      - ./application:/var/www/html
  database:
    image: mariadb:11.7.2
    container_name: "database-container"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_DATABASE: shop
      MARIADB_USER: user
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: rootsecret
    volumes:
      - mysqldata:/var/lib/mysql
  cache:
    image: redis:alpine
    container_name: "cache-container"
    ports:
      - "6379:6379"

volumes:
  mysqldata:
